{
    "0": "Ofuda of the Moon \"Moonlight Ray\"",
    "1": "Ofuda of the Night \"Night Bird\"",
    "2": "Ofuda of Darkness \"Demarcation\"",
    "3": "Ofuda of Ice \"Icicle Fall\"",
    "4": "Ofuda of Hail \"Hailstorm\"",
    "5": "Ofuda of Freezing \"Perfect Freeze\"",
    "6": "Snow Ofuda \"Diamond Blizzard\"",
    "7": "Ofuda of Flowers \"Gorgeous Sweet Flower\"",
    "8": "Ofuda of Flowers \"Selaginella 9\"",
    "9": "Rainbow Ofuda \"Colorful Rainbow Wind Chime\"",
    "10": "Ofuda of Illusion \"Imaginary Flower Yumekazura\"",
    "11": "Colorful Ofuda \"Colorful Rain\"",
    "12": "Colorful Ofuda \"Vivid Chaotic Dance\"",
    "13": "Colorful Ofuda \"Dazzling Color Typhoon\"",
    "14": "Ofuda of Fire \"Agni Shine\"",
    "15": "Ofuda of Water \"Princess Undine\"",
    "16": "Ofuda of Wood \"Sylphy Horn\"",
    "17": "Ofuda of the Earth \"Lazy Trilithon\"",
    "18": "Ofuda of Metal \"Metal Fatigue\"",
    "19": "Ofuda of Fire \"Agni Shine High Level\"",
    "20": "Ofuda of Wood \"Sylphy Horn High Level\"",
    "21": "Ofuda of the Earth \"Lazy Trilithon High Level\"",
    "22": "Ofuda of Fire \"Agni Radiance\"",
    "23": "Ofuda of Water \"Bury In Lake\"",
    "24": "Ofuda of Wood \"Green Storm\"",
    "25": "ofud of the Earth \"Trilithon Shake\"",
    "26": "Ofuda of Metal \"Silver Dragon\"",
    "27": "Ofuda of Fire & the Earth \"Lava Cromlech\"",
    "28": "Ofuda of Wood & Fire \"Forest Blaze\"",
    "29": "Ofuda of Water & Wood \"Water Elf\"",
    "30": "Ofuda of Metal & Water \"Mercury Poison\"",
    "31": "Ofuda of the Earth & Metal \"Emerald Megalith\"",
    "32": "Conjuring \"Misdirection\"",
    "33": "Conjuring \"Mesmerizing Misdirection\"",
    "34": "Illusion Existence \"Clock Corpse\"",
    "35": "Illusion Image \"Luna Clock\"",
    "36": "Maid Secret Skill \"Manipulating Doll\"",
    "37": "Illusion Phantom \"Jack the Ludo Bile\"",
    "38": "Illusion World \"The World\"",
    "39": "Maid Secret Skill \"Killing Doll\"",
    "40": "Conjuring \"Eternal Meek\"",
    "41": "Heaven's Punishment \"Star of David\"",
    "42": "Nether Sign \"Scarlet Netherworld\"",
    "43": "Curse \"Curse of Vlad Țepeș\"",
    "44": "Scarlet Sign \"Scarlet Shoot\"",
    "45": "\"Red Magic\"",
    "46": "God's Punishment \"Young Demon Lord\"",
    "47": "Hell Sign \"Mountain of a Thousand Needles\"",
    "48": "Divine Art \"Vampire Illusion\"",
    "49": "Scarlet Sign \"Scarlet Meister\"",
    "50": "\"Scarlet Gensokyo\"",
    "51": "Moon Sign \"Silent Selene\"",
    "52": "Sun Sign \"Royal Flare\"",
    "53": "Fire Water Wood Metal Earth Sign \"Philosopher's Stone\"",
    "54": "Taboo \"Cranberry Trap\"",
    "55": "Taboo \"Lævateinn\"",
    "56": "Taboo \"Four of a Kind\"",
    "57": "Taboo \"Kagome, Kagome\"",
    "58": "Taboo \"Maze of Love\"",
    "59": "Forbidden Barrage \"Starbow Break\"",
    "60": "Forbidden Barrage \"Catadioptric\"",
    "61": "Forbidden Barrage \"Clock that Ticks Away the Past\"",
    "62": "Secret Barrage \"And Then Will There Be None?\"",
    "63": "Q.E.D. \"Ripples of 495 Years\""
}